# Generated by Django 3.2 on 2021-10-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(help_text='Date time on which the object was deleted.', null=True, verbose_name='deleted at'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(help_text='Date time on which the object was deleted.', null=True, verbose_name='deleted at'),
        ),
    ]
