# Generated by Django 3.2 on 2021-10-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211002_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Set to true if user wants profile to be visible.', verbose_name='is public'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True, help_text="Set to true when the user has verified it's email address.", verbose_name='verified'),
        ),
    ]
