# Generated by Django 3.2 on 2021-10-11 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_abstract_concepts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='idea',
            new_name='name',
        ),
    ]
