# Generated by Django 3.2 on 2021-10-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_ideas_questions_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ideas',
            field=models.ManyToManyField(blank=True, null=True, related_name='child_questions', to='ideas.Idea'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='questions',
            field=models.ManyToManyField(related_name='child_ideas', to='ideas.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
