# Generated by Django 3.2 on 2021-10-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_ideas_questions_cyclic_dependency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ideas',
            field=models.ManyToManyField(blank=True, related_name='child_questions', to='ideas.Idea'),
        ),
    ]
