# Generated by Django 3.2 on 2021-10-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comments_feed_reaction_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='comments',
            new_name='comment',
        ),
    ]
